# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-27 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=200)),
                ('Proficiency_Level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced'), ('E', 'Expert'), ('O', 'Other')], max_length=100)),
                ('Start_Date', models.DateField(blank=True, null=True)),
                ('Expiration_Date', models.DateField(blank=True, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization', models.CharField(max_length=200)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Body', models.TextField()),
                ('Company', models.CharField(max_length=200)),
                ('Position', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institution', models.CharField(max_length=200)),
                ('Street_Address', models.CharField(blank=True, max_length=250, null=True)),
                ('City', models.CharField(blank=True, max_length=200, null=True)),
                ('State', models.CharField(blank=True, max_length=200, null=True)),
                ('Zip_Code', models.IntegerField(blank=True, null=True)),
                ('Start_Date', models.DateField(blank=True, null=True)),
                ('End_Date', models.DateField(blank=True, null=True)),
                ('Subject', models.CharField(max_length=200)),
                ('Completed', models.BooleanField()),
                ('Link', models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=250)),
                ('Last_Name', models.CharField(max_length=250)),
                ('Street_Address', models.CharField(max_length=250)),
                ('City', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Zip_Code', models.IntegerField()),
                ('Phone_Number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Authors', models.TextField()),
                ('Type', models.CharField(max_length=100)),
                ('Publisher', models.CharField(max_length=200)),
                ('Pub_City', models.CharField(max_length=200)),
                ('Pub_Year', models.IntegerField()),
                ('Volume', models.CharField(blank=True, max_length=200, null=True)),
                ('Issue', models.CharField(blank=True, max_length=200, null=True)),
                ('Pages', models.CharField(blank=True, max_length=200, null=True)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_history.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=250)),
                ('Last_Name', models.CharField(max_length=250)),
                ('Street_Address', models.CharField(blank=True, max_length=250, null=True)),
                ('City', models.CharField(blank=True, max_length=200, null=True)),
                ('State', models.CharField(blank=True, max_length=200, null=True)),
                ('Zip_Code', models.IntegerField(blank=True, null=True)),
                ('Phone_Number', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Type', models.CharField(choices=[('Pro', 'Professional'), ('Per', 'Personal'), ('Both', 'Both'), ('Other', 'Other')], max_length=50)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_history.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=200)),
                ('Proficiency_Level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced'), ('E', 'Expert'), ('O', 'Other')], max_length=100)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_history.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_history.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employer', models.CharField(max_length=200)),
                ('Job_Title', models.CharField(max_length=200)),
                ('Start_Date', models.DateField(blank=True, null=True)),
                ('End_Date', models.DateField(blank=True, null=True)),
                ('Schedule', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('Temp', 'Temporary'), ('Term', 'Term'), ('other', 'other')], max_length=50)),
                ('Starting_Salary', models.IntegerField()),
                ('Ending_Salary', models.IntegerField()),
                ('Position_Description', models.TextField()),
                ('Supervisor_First_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Supervisor_Last_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Supervisor_Phone', models.BigIntegerField(blank=True, null=True)),
                ('Supervisor_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_history.PersonalInfo')),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='Person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_history.PersonalInfo'),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='Person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_history.PersonalInfo'),
        ),
        migrations.AddField(
            model_name='community',
            name='Person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_history.PersonalInfo'),
        ),
        migrations.AddField(
            model_name='certifications',
            name='Person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_history.PersonalInfo'),
        ),
    ]
