# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-27 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='Link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Phone_Number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='Phone_Number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
