# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-27 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_history', '0002_auto_20170827_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='GPA',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
    ]
