# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-28 01:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_history', '0005_auto_20170827_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
