# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-28 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_history', '0006_auto_20170827_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='Achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='Position',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='Achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='Notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='Organization',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='Supervisor_Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='Supervisor_First_Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='Supervisor_Last_Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='Supervisor_Phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='Work_Performed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='Ending_Salary',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='Starting_Salary',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
