# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_history', '0007_auto_20170827_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
